import { ListProviderProps, ProviderDetailProps } from '@ffp-web/app/index.types';

export const providerListMock: ListProviderProps[] = [
  {
    providerId: 'P001',
    fullName: 'Emily Johnson',
    businessName: 'Johnson Tours and Adventures',
    email: 'emily.johnson@gmail.com',
    countryName: 'United States',
    cityName: 'San Francisco',
    isApproved: true,
  },
  {
    providerId: 'P002',
    fullName: 'Ricardo Silva',
    businessName: 'Silva Fitness Center',
    email: 'silva@gmail.com',
    countryName: 'United States',
    cityName: 'New York',
    isApproved: false,
  },
  {
    providerId: 'P003',
    fullName: 'Aditi Verma',
    businessName: 'Verma Yoga Studio',
    email: 'verma@outlook.com',
    countryName: 'India',
    cityName: 'New Delhi',
    isApproved: true,
  },
  {
    providerId: 'P004',
    fullName: 'Michael Brown',
    businessName: 'Brown\'s Fitness',
    email: 'michael.brown@gmail.com',
    countryName: 'United Kingdom',
    cityName: 'London',
    isApproved: false,
  },
  {
    providerId: 'P005',
    fullName: 'Sophia Lee',
    businessName: 'Lee’s Culinary Classes',
    email: 'sophia.lee@example.com',
    countryName: 'Canada',
    cityName: 'Toronto',
    isApproved: true,
  },
  {
    providerId: 'P006',
    fullName: 'Carlos Martinez',
    businessName: 'Martinez Photography Studio',
    email: 'carlos.martinez@example.com',
    countryName: 'Spain',
    cityName: 'Barcelona',
    isApproved: true,
  },
  {
    providerId: 'P007',
    fullName: 'Hannah Smith',
    businessName: 'Smith Event Planners',
    email: 'hannah.smith@events.com',
    countryName: 'United Kingdom',
    cityName: 'Manchester',
    isApproved: false,
  },
  {
    providerId: 'P008',
    fullName: 'Ahmed Khan',
    businessName: 'Khan Tech Solutions',
    email: 'ahmed.khan@techsolutions.com',
    countryName: 'United Arab Emirates',
    cityName: 'Dubai',
    isApproved: true,
  },
  {
    providerId: 'P009',
    fullName: 'Jessica Taylor',
    businessName: 'Taylor Art Workshops',
    email: 'jessica.taylor@artworkshops.com',
    countryName: 'United States',
    cityName: 'Los Angeles',
    isApproved: true,
  },
  {
    providerId: 'P010',
    fullName: 'Liam O’Connor',
    businessName: 'O’Connor Music Academy',
    email: 'liam.oconnor@musicacademy.com',
    countryName: 'Ireland',
    cityName: 'Dublin',
    isApproved: false,
  },
];

export const providerDetailsMock: ProviderDetailProps[] = [
  {
    providerId: 'P001',
    fullName: 'Emily Johnson',
    businessName: 'Johnson Tours and Adventures',
    email: 'emily.johnson@gmail.com',
    phoneNumber: '+1 (555) 123-4567',
    countryName: 'United States',
    cityName: 'San Francisco',
    isApproved: true,
    categoryName: 'Travel and Tourism',
    description:
      'We provide guided city tours, adventure packages, and personalized travel experiences in California.',
    targetAudience: 'Tourists, families, and adventure seekers',
    location: 'California, USA',
    yearInOperation: '5 years',
    website: 'www.johnsontours.com',
    instagram: '@johnson_tours',
    facebook: 'facebook.com/johnsontours',
    tiktok: '@johnsontoursfu',
    youtube: 'youtube.com/johnsontours',
    snapchat: '@johnsontours_snap',
    certification: 'travel_license.pdf',
    businessRegNumber: '123-45-678',
  },
  {
    providerId: 'P002',
    fullName: 'Ricardo Silva',
    businessName: 'Silva Fitness Center',
    email: 'silva@gmail.com',
    phoneNumber: '+1 (444) 987-6543',
    countryName: 'United States',
    cityName: 'New York',
    isApproved: false,
    categoryName: 'Fitness and Health',
    description:
      'We offer comprehensive gym facilities, personal training programs, and group fitness classes.',
    targetAudience: 'Fitness enthusiasts, gym-goers, and athletes',
    location: 'New York, USA',
    yearInOperation: '8 years',
    website: 'www.silvafitness.com',
    instagram: '@silvafitness',
    facebook: 'facebook.com/silvafitness',
    tiktok: '@silvafitnessfun',
    youtube: 'youtube.com/silvafitness',
    snapchat: '@silva_snap',
    certification: 'silva_certification.pdf',
    businessRegNumber: '456-78-910',
  },
  {
    providerId: 'P003',
    fullName: 'Aditi Verma',
    businessName: 'Verma Yoga Studio',
    email: 'verma@outlook.com',
    phoneNumber: '+91 98765 43210',
    countryName: 'India',
    cityName: 'New Delhi',
    isApproved: true,
    categoryName: 'Yoga and Wellness',
    description:
      'We specialize in yoga classes for stress relief, fitness improvement, and mental clarity.',
    targetAudience: 'Yoga practitioners, wellness seekers, and beginners',
    location: 'New Delhi, India',
    yearInOperation: '10 years',
    website: 'www.vermastudio.com',
    instagram: '@verma_yoga',
    facebook: 'facebook.com/vermastudio',
    tiktok: '@vermayogastudio',
    youtube: 'youtube.com/vermastudio',
    snapchat: '@vermastudio_snap',
    businessRegNumber: '789-01-234',
  },
  {
    providerId: 'P004',
    fullName: 'Michael Brown',
    businessName: 'Brown\'s Fitness',
    email: 'michael.brown@gmail.com',
    phoneNumber: '+44 7789 123456',
    countryName: 'United Kingdom',
    cityName: 'London',
    isApproved: false,
    categoryName: 'Fitness Training',
    description:
      'We provide fitness boot camps, personal coaching, and strength training programs.',
    targetAudience: 'Fitness beginners, bodybuilders, and gym-goers',
    location: 'London, United Kingdom',
    yearInOperation: '6 years',
    website: 'www.brownsfitness.co.uk',
    instagram: '@brownsfitness',
    facebook: 'facebook.com/brownsfitness',
    tiktok: '@brownsfitness',
    youtube: 'youtube.com/brownsfitness',
    snapchat: '@brownsfitness_snap',
    certification: 'fitness_license.pdf',
    businessRegNumber: '567-89-012',
  },
  {
    providerId: 'P005',
    fullName: 'Sophia Lee',
    businessName: 'Lee’s Culinary Classes',
    email: 'sophia.lee@example.com',
    phoneNumber: '+1 (647) 555-7890',
    countryName: 'Canada',
    cityName: 'Toronto',
    isApproved: true,
    categoryName: 'Cooking Classes',
    description:
      'We provide hands-on culinary classes, baking workshops, and professional chef training.',
    targetAudience: 'Food enthusiasts, home cooks, and aspiring chefs',
    location: 'Toronto, Canada',
    yearInOperation: '7 years',
    website: 'www.leeculinary.com',
    instagram: '@lee_culinary',
    facebook: 'facebook.com/lee_culinary',
    tiktok: '@lee_culinary_fun',
    youtube: 'youtube.com/lee_culinary',
    snapchat: '@lee_culinary_snap',
    businessRegNumber: '234-56-789',
  },
  {
    providerId: 'P006',
    fullName: 'Carlos Martinez',
    businessName: 'Martinez Photography Studio',
    email: 'carlos.martinez@example.com',
    phoneNumber: '+34 612 345 678',
    countryName: 'Spain',
    cityName: 'Barcelona',
    isApproved: true,
    categoryName: 'Photography Services',
    description:
      'We specialize in professional photography services, including portraits, weddings, and commercial shoots.',
    targetAudience: 'Couples, businesses, and event organizers',
    location: 'Barcelona, Spain',
    yearInOperation: '4 years',
    website: 'www.martinezstudio.com',
    instagram: '@martinez_photography',
    facebook: 'facebook.com/martinezstudio',
    tiktok: '@martinezphotos',
    youtube: 'youtube.com/martinezstudio',
    snapchat: '@martinez_snap',
    businessRegNumber: '654-32-109',
  },
  {
    providerId: 'P007',
    fullName: 'Hannah Smith',
    businessName: 'Smith Event Planners',
    email: 'hannah.smith@events.com',
    phoneNumber: '+44 7890 123456',
    countryName: 'United Kingdom',
    cityName: 'Manchester',
    isApproved: false,
    categoryName: 'Event Planning',
    description:
      'We organize and plan events such as weddings, corporate functions, and private parties.',
    targetAudience: 'Event hosts, corporate clients, and families',
    location: 'Manchester, United Kingdom',
    yearInOperation: '9 years',
    website: 'www.smithevents.com',
    instagram: '@smith_events',
    facebook: 'facebook.com/smithevents',
    tiktok: '@smitheventsfun',
    youtube: 'youtube.com/smithevents',
    snapchat: '@smith_events_snap',
    certification: 'event_certification.pdf',
    businessRegNumber: '321-45-987',
  },
  {
    providerId: 'P008',
    fullName: 'Ahmed Khan',
    businessName: 'Khan Tech Solutions',
    email: 'ahmed.khan@techsolutions.com',
    phoneNumber: '+971 50 987 6543',
    countryName: 'United Arab Emirates',
    cityName: 'Dubai',
    isApproved: true,
    categoryName: 'Technology Services',
    description:
      'We offer IT consulting, software development, and cloud solutions for businesses of all sizes.',
    targetAudience: 'Small to medium businesses and enterprises',
    location: 'Dubai, UAE',
    yearInOperation: '6 years',
    website: 'www.khantechsolutions.com',
    instagram: '@khan_tech',
    facebook: 'facebook.com/khantechsolutions',
    tiktok: '@khantech',
    youtube: 'youtube.com/khantech',
    snapchat: '@khan_tech_snap',
    businessRegNumber: '789-65-432',
  },
  {
    providerId: 'P009',
    fullName: 'Jessica Taylor',
    businessName: 'Taylor Art Workshops',
    email: 'jessica.taylor@artworkshops.com',
    phoneNumber: '+1 (213) 456-7890',
    countryName: 'United States',
    cityName: 'Los Angeles',
    isApproved: true,
    categoryName: 'Art and Creativity',
    description:
      'We offer hands-on art classes for all ages, including painting, drawing, and sculpture workshops.',
    targetAudience: 'Art enthusiasts, children, and adults',
    location: 'Los Angeles, USA',
    yearInOperation: '3 years',
    website: 'www.taylorartworkshops.com',
    instagram: '@taylor_art',
    facebook: 'facebook.com/taylorartworkshops',
    tiktok: '@taylorartfun',
    youtube: 'youtube.com/taylorartworkshops',
    snapchat: '@taylor_art_snap',
    certification: 'art_certification.pdf',
    businessRegNumber: '456-78-101',
  },
  {
    providerId: 'P010',
    fullName: 'Liam O’Connor',
    businessName: 'O’Connor Music Academy',
    email: 'liam.oconnor@musicacademy.com',
    phoneNumber: '+353 87 123 4567',
    countryName: 'Ireland',
    cityName: 'Dublin',
    isApproved: false,
    categoryName: 'Music Lessons',
    description:
      'We provide music lessons for guitar, piano, and vocals, tailored for beginners and advanced learners.',
    targetAudience: 'Music learners, students, and enthusiasts',
    location: 'Dublin, Ireland',
    yearInOperation: '8 years',
    website: 'www.oconnormusic.com',
    instagram: '@oconnor_music',
    facebook: 'facebook.com/oconnormusicacademy',
    tiktok: '@oconnormusic',
    youtube: 'youtube.com/oconnormusic',
    snapchat: '@oconnor_music_snap',
    businessRegNumber: '987-65-321',
  },
];
